# Rasmiy Python bazasi
FROM python:3.10-slim

# Ishchi katalog
WORKDIR /app

# ffmpeg o‘rnatamiz
RUN apt-get update && apt-get install -y ffmpeg

# Fayllarni nusxalash
COPY . .

# Python kutubxonalarini o‘rnatish
RUN pip install --no-cache-dir -r requirements.txt

# Port sozlash
EXPOSE 8080

# Flask ilovani ishga tushirish
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:8080"]
